[pronunciations]
# Use this to correct the pronunciation of words that
# are spelled differently from how they are pronounced.
# The format is:
#   word = pronunciation
# where word is case insensitive
