[main]
level = "debug"                                                  # debug, info, warning, error, fatal
reload = false                                                   # if true, delete the old log file and create a new one
format = "{asctime} | {name: <15} | {levelname: <8} | {message}" # format of the log file

[[main.handlers]]
type = "file"   # type of the handler
level = "debug" # debug, info, warning, error, fatal

[[main.handlers]]
type = "stdout"    # type of the handler
level = "critical" # debug, info, warning, error, fatal
