[interfaces]
[interfaces.cli]
input = { text = true }                   # types of input this interface supports
outputs = { text = true, speech = true }  # types of output this interface supports
headers = { text = true, speech = false } # types of headers this interface supports

[interfaces.gui]
input = { text = true }                   # types of input this interface supports
outputs = { text = true, speech = true }  # types of output this interface supports
headers = { text = true, speech = false } # types of headers this interface supports
theme = "dracula"                         # theme to use for the GUI


[colour_schemes]
[colour_schemes.dracula]
background = "#282A36"
current_line = "#44475A"
foreground = "#F8F8F2"
comment = "#6272A4"
cyan = "#8bE9FD"
green = "#50FA7B"
orange = "#FFb86C"
pink = "#FF79C6"
purple = "#BD93F9"
red = "#FF5555"
yellow = "#F1fA8C"
